/* XZB */

#define BOARD_PID		  "XY-C1"
#define BOARD_NAME		"XZB (TimeCloud)"
#define BOARD_DESC		"Xunlei XZB (TimeCloud)"
#define BOARD_VENDOR_NAME	"Xunlei(Shenzheng) Limited"
#define BOARD_VENDOR_URL	"http://www.xunlei.com/"
#define BOARD_MODEL_URL		"http://www.xunlei.com/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_BTN_RESET	13
#define BOARD_GPIO_BTN_WPS	4
#define BOARD_GPIO_SWICH_SD	43
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#undef  BOARD_GPIO_LED_POWER
#undef  BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_WAN

#define  BOARD_ROLE_REPEATER  1

#define	 BOARD_GPIO_LED_USB	7
#define  BOARD_GPIO_LED_ROUTER	8
#define  BOARD_GPIO_PWR_USB	11

#undef BOARD_HAS_5G_11AC
#undef BOARD_NUM_ANT_5G_TX
#undef BOARD_NUM_ANT_5G_RX
#undef BOARD_NUM_ANT_2G_TX
#undef BOARD_NUM_ANT_2G_RX
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1

#define BOARD_GPIO_PWR_USB_ON	1
#define BOARD_USB_PORT_SWAP	0
